### ISSUE TITLE
MIRICLE build failing in DHAS

### ISSUE THREAD

**Issue by vcgeers** [JWST-MIRI/DHAS#47]
Hi Jane,

It looks like the most recent MIRICLE devel builds are failing during compilation of DHAS:
https://jenkins.miricle.org/job/BuildDevel38/788/

The first bit of the log where it goes wrong states:

> [...truncated 419.34 KB...]
> In file included from /usr/include/c++/8/istream:39,
>                 from /usr/include/c++/8/backward/strstream:53,
>                 from include/miri_data_info.h:5,
>                 from include/miri_sloper.h:4,
>                 from ms_read_RSCD_file.cpp:3:
> /usr/include/c++/8/ostream:511:5: note: candidate: ‘template<class _Traits> std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, char)’
>     operator<<(basic_ostream<char, _Traits>& __out, char __c)
>     ^~~~~~~~
> /usr/include/c++/8/ostream:511:5: note:   template argument deduction/substitution failed:
> ms_read_RSCD_file.cpp:290:7: note:   cannot convert ‘std::cout’ (type ‘std::ostream’ {aka ‘std::basic_ostream<char>’}) to type ‘char’
>       cout << " Turning off apply rscd correction " << endl;
>       ^~~~

Those lines haven't been changed in a while, so I'm not sure why it would cause an issue now.

I'm not experienced with the C++ code, but I wonder whether it could be that on this line:
https://github.com/JWST-MIRI/DHAS/blob/66f90cf72a6c8bf0b6b622ea9f23678cf016897a/MPipeline/DAT/src_ms/ms_read_RSCD_file.cpp#L289
the trailing "<<" aren't supposed to be there?  (maybe some compilers can handle those more gracefully than others)

Could you please have a look?

**Comment by jemorrison** [comment]
It should be fixed now. I just pushed over the fix

**Comment by vcgeers** [comment]
Great, thank you for the quick fix Jane.

Latest build got past DHAS compilation alright, so I believe this is resolved now.
(build did fail, but in a different step, so following that up separately with Wim)

Thanks again.
